"""Pure-Python secp256k1 ECDSA: sign, recover, address derivation.

The x402 "exact" scheme on EVM is an EIP-3009 `transferWithAuthorization` signed by
the payer. To produce a payment header a client must sign a real EIP-712 digest with
a real key, and the facilitator must recover a real address from it. This repo has no
`eth_account` / `coincurve` available in its environment, so the curve math lives
here: RFC 6979 deterministic nonces, EIP-2 low-`s` normalisation, and the recovery id
that Ethereum's `ecrecover` expects.

The signatures produced here are consumed unmodified by Solidity. `test/X402Claim.t.sol`
feeds a vector generated by this module into `MockERC20.transferWithAuthorization`,
which calls `ecrecover`; if the math here were wrong that Foundry test would revert.
`tests/test_x402.py::test_solidity_vector_matches_python_signer` regenerates the same
vector and pins it against the checked-in Solidity fixture, so the two languages
cannot silently drift apart.
"""

from __future__ import annotations

import hashlib
import hmac

from .hashing import keccak256

# secp256k1 domain parameters
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
A = 0
B = 7
GX = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
GY = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8

_Point = tuple[int, int] | None  # None is the point at infinity


def _inv(x: int, m: int) -> int:
    return pow(x, -1, m)


def _add(p: _Point, q: _Point) -> _Point:
    if p is None:
        return q
    if q is None:
        return p
    (x1, y1), (x2, y2) = p, q
    if x1 == x2 and (y1 + y2) % P == 0:
        return None
    if p == q:
        lam = (3 * x1 * x1 + A) * _inv(2 * y1, P) % P
    else:
        lam = (y2 - y1) * _inv(x2 - x1, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)


def _mul(k: int, p: _Point) -> _Point:
    r: _Point = None
    while k:
        if k & 1:
            r = _add(r, p)
        p = _add(p, p)
        k >>= 1
    return r


def _decompress(x: int, odd: bool) -> _Point:
    """Recover the curve point with abscissa `x` and the requested y parity."""
    if x >= P:
        return None
    alpha = (pow(x, 3, P) + A * x + B) % P
    beta = pow(alpha, (P + 1) // 4, P)
    if pow(beta, 2, P) != alpha:
        return None  # x is not on the curve
    y = beta if (beta % 2 == 1) == odd else P - beta
    return (x, y)


def _rfc6979_k(priv: int, digest: bytes) -> int:
    """Deterministic nonce (RFC 6979, HMAC-SHA256) so signing is reproducible."""
    v = b"\x01" * 32
    k = b"\x00" * 32
    priv_b = priv.to_bytes(32, "big")
    k = hmac.new(k, v + b"\x00" + priv_b + digest, hashlib.sha256).digest()
    v = hmac.new(k, v, hashlib.sha256).digest()
    k = hmac.new(k, v + b"\x01" + priv_b + digest, hashlib.sha256).digest()
    v = hmac.new(k, v, hashlib.sha256).digest()
    while True:
        v = hmac.new(k, v, hashlib.sha256).digest()
        cand = int.from_bytes(v, "big")
        if 1 <= cand < N:
            return cand
        k = hmac.new(k, v + b"\x00", hashlib.sha256).digest()
        v = hmac.new(k, v, hashlib.sha256).digest()


def public_key(priv: int) -> bytes:
    """Uncompressed public key bytes (64 bytes, no 0x04 prefix)."""
    if not 1 <= priv < N:
        raise ValueError("private key out of range")
    pt = _mul(priv, (GX, GY))
    assert pt is not None
    return pt[0].to_bytes(32, "big") + pt[1].to_bytes(32, "big")


def address_of(priv: int) -> str:
    """Ethereum address controlled by `priv`, checksummed."""
    return to_checksum("0x" + keccak256(public_key(priv))[12:].hex())


def sign(priv: int, digest: bytes) -> tuple[int, bytes, bytes]:
    """Sign a 32-byte digest. Returns Ethereum's (v, r, s) with v in {27, 28}."""
    if len(digest) != 32:
        raise ValueError("digest must be 32 bytes")
    z = int.from_bytes(digest, "big")
    k = _rfc6979_k(priv, digest)
    while True:
        pt = _mul(k, (GX, GY))
        assert pt is not None
        r = pt[0] % N
        if r != 0:
            s = (_inv(k, N) * (z + r * priv)) % N
            if s != 0:
                break
        k = (k + 1) % N
    recovery = (pt[1] & 1) ^ (1 if pt[0] >= N else 0)
    if s > N // 2:  # EIP-2: only low-s signatures are canonical on Ethereum
        s = N - s
        recovery ^= 1
    return 27 + recovery, r.to_bytes(32, "big"), s.to_bytes(32, "big")


def recover(digest: bytes, v: int, r: bytes, s: bytes) -> str | None:
    """Address that produced (v, r, s) over `digest`, or None if unrecoverable.

    Mirrors Solidity `ecrecover`: rejects out-of-range r/s, non-canonical high-s,
    and v outside {27, 28} by returning None rather than a bogus address.
    """
    if len(r) != 32 or len(s) != 32 or v not in (27, 28):
        return None
    ri = int.from_bytes(r, "big")
    si = int.from_bytes(s, "big")
    if not (1 <= ri < N) or not (1 <= si <= N // 2):
        return None
    pt = _decompress(ri, odd=bool(v - 27))
    if pt is None:
        return None
    z = int.from_bytes(digest, "big")
    r_inv = _inv(ri, N)
    q = _add(_mul(si * r_inv % N, pt), _mul((N - z) * r_inv % N, (GX, GY)))
    if q is None:
        return None
    pub = q[0].to_bytes(32, "big") + q[1].to_bytes(32, "big")
    return to_checksum("0x" + keccak256(pub)[12:].hex())


def to_checksum(addr: str) -> str:
    """EIP-55 checksummed address."""
    low = addr.lower().removeprefix("0x")
    if len(low) != 40:
        raise ValueError("address must be 20 bytes")
    h = keccak256(low.encode("ascii")).hex()
    return "0x" + "".join(c.upper() if c.isalpha() and int(h[i], 16) >= 8 else c for i, c in enumerate(low))
